<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.12.2" name="Text (Black) (8x10)" tilewidth="8" tileheight="10" tilecount="50" columns="10">
 <image source="../../assets/Menu/Text/Text (Black) (8x10).png" width="80" height="50"/>
 <tile id="0" type="a"/>
 <tile id="1" type="b"/>
 <tile id="2" type="c"/>
 <tile id="3" type="s"/>
 <tile id="4" type="e"/>
 <tile id="5" type="f"/>
 <tile id="6" type="g"/>
 <tile id="7" type="h"/>
 <tile id="8" type="i"/>
 <tile id="9" type="j"/>
 <tile id="10" type="k"/>
 <tile id="11" type="l"/>
 <tile id="12" type="m"/>
 <tile id="13" type="n"/>
 <tile id="14" type="o"/>
 <tile id="15" type="p"/>
 <tile id="16" type="q"/>
 <tile id="17" type="r"/>
 <tile id="18" type="s"/>
 <tile id="19" type="t"/>
 <tile id="20" type="u"/>
 <tile id="21" type="v"/>
 <tile id="22" type="w"/>
 <tile id="23" type="x"/>
 <tile id="24" type="y"/>
 <tile id="25" type="z"/>
 <tile id="30" type="0"/>
 <tile id="31" type="1"/>
 <tile id="32" type="2"/>
 <tile id="33" type="3"/>
 <tile id="34" type="4"/>
 <tile id="35" type="5"/>
 <tile id="36" type="6"/>
 <tile id="37" type="7"/>
 <tile id="38" type="8"/>
 <tile id="39" type="9"/>
 <tile id="40" type="dot"/>
 <tile id="41" type="colan"/>
 <tile id="42" type="semi_colan"/>
 <tile id="43" type="question"/>
 <tile id="44" type="exclamation"/>
 <tile id="45" type="bracet_open"/>
 <tile id="46" type="bracet_close"/>
 <tile id="47" type="plus"/>
 <tile id="48" type="minus"/>
</tileset>
